<?php
/**
 * @file
 * Install, update and uninstall functions for the ting_search_carousel module.
 */

/**
 * Implements hook_install().
 */
function ting_search_carousel_install() {
  $path = file_directory_path() . '/' . 'ting_search_carousel';
  file_check_directory($path, FILE_CREATE_DIRECTORY);
}

/**
 * Implements hook_uninstall().
 */
function ting_search_carousel_uninstall() {
  variable_del('ting_carousel_search_queries_hidden');
  variable_del('ting_carousel_search_queries');
}
