<?php
/**
 * @file
 * Author portrait block module.
 */

/**
 * Implements hook_theme().
 */
function ebog_author_portrait_theme() {
  return array(
    'ebog_author_portrait_block' => array(
      'arguments' => array(
        'image' => NULL,
        'name' => NULL,
        'description' => NULL,
        'more_link' => NULL,
      ),
      'template' => 'templates/ebog_author_portrait_block',
    ),
  );
}

/**
 * Implements hook_block().
 */
function ebog_author_portrait_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();

  switch ($op) {
    case 'list':
      $block = array(
        array(
          'info' => t('Ebog Author Portrait'),
        ),
      );
      break;

    case 'view':
      $block = array(
        'subject' => t('Ebog Author Portrait'),
        'content' => _ebog_author_portrait_block_view(),
      );
      break;
  }

  return $block;
}

/**
 * Block renderer method.
 *
 * @return string
 *   Block content markup.
 *
 * @see ebog_author_portrait_block()
 */
function _ebog_author_portrait_block_view() {
  $node = NULL;
  $content = '';

  $result = db_query('SELECT nid FROM {node} WHERE type = "portrait" AND status = 1 ORDER BY created DESC LIMIT 1');
  while ($row = db_fetch_array($result)) {
    drupal_add_css(drupal_get_path('module', 'ebog_author_portrait') . '/css/ebog_author_portrait_style.css', 'file');

    $node = node_load($row['nid']);
    $image = $node->field_portrait_image[0]['filepath'];
    $name = $node->field_portrait_author[0]['value'];
    $description = $node->body;
    $more_link = l($node->field_portrait_more_link[0]['value'], $node->field_portrait_more_link_url[0]['value']);

    $content = theme('ebog_author_portrait_block', $image, $name, $description, $more_link);
  }

  return $content;
}
