<?php

/**
 * Implements hook_menu().
 */
function netsound_cart_menu() {
  $items = array();

  $items['ting/object/%/huskeliste'] = array(
    'title' => t('Tilføj til huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2, 'add'),
    'access arguments' => array('access content'),
  );

  $items['ting/object/%/huskeliste/fjern'] = array(
    'title' => t('Fjern fra huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2, 'delete'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Modify the contents of a given users netsound cart.
 *
 * @global object $user
 *  Currently logged in global user object.
 * @param type $ting_object_id
 *  Ting datawall object id.
 * @param type $op
 *  Operation to preform on the cart.
 *
 */
function netsound_cart_modify($ting_object_id, $op) {
  global $user;

  // If the current user is valid and logged in.
  if ($user->uid != 0) {
    // Load the ting client to make request to the datawell.
    module_load_include('client.inc', 'ting');
    $object = ting_get_object_by_id($ting_object_id);

    // Check that we got a ting object
    if ($object instanceof TingClientObject) {
      $params = array(
          'uid' => $user->uid,
          'ting_object_id' => $object->id,
      );
      switch ($op) {
        case 'add':
          $params['tstamp'] = time();
          drupal_write_record('netsound_cart', $params);
          drupal_set_message(t('!book er nu tilføjet din huskeliste', array('!book' => l($object->title, 'ting/object/' . $object->id))));
          break;

        case 'delete':
          db_query('DELETE FROM {netsound_cart}
                          WHERE uid = %s
                            AND ting_object_id = "%s"', $user->uid, $object->id);
          drupal_set_message(t('!book er nu fjernet fra din huskeliste', array('!book' => l($object->title, 'ting/object/' . $object->id))));
          break;
      }
      _netsound_cart_cache_clear($user->uid);
      drupal_goto();
    }

    // @TODO: What if its not an ting object ?
  }
}

/**
 * Creates a add to cart link.
 *
 * @param type $ting_object_id
 * @return type
 */
function netsound_cart_add_link($ting_object_id) {
  $uri = 'ting/object/' . $ting_object_id . '/huskeliste';
  $options = array(
    'query' => drupal_get_destination(),
    'attributes' => array(
      'class' => 'addtocart'
    )
  );
  return l(t('Tilføj til huskeliste'), uri, $options);
}

/**
 * Implements hook_block().
 *
 * Provides the "My lists" block with information about the books placed in the
 * cart.
 *
 * @TODO implement cache for this list.
 */
function netsound_cart_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('What\'s in my cart?');
      break;

    case 'view':
      // Get current logged in user.
      global $user;

      // Set default block title.
      $blocks['subject'] = t('Min huskeliste');

      $content = _netsound_cart_cache_get($user->uid);
      if ($content == FALSE) {

        // Load the ting client.
        module_load_include('client.inc', 'ting');

        // Load cart form the database and extra information form the datawell.
        $rows = array();
        $result = db_query('SELECT DISTINCT ting_object_id
                                      FROM {netsound_cart}
                                      WHERE uid = %d', array('%d' => $user->uid));
        while ($row = db_fetch_array($result)) {
          $object = ting_get_object_by_id($row['ting_object_id']);

          // HACK XXXX, the objects saved in the cart may not longer exists
          // in the datawell. So if they do not have ISBN number, we have to
          // remove them from the cart.
          if (!isset($object->record['dc:identifier']['oss:PROVIDER-ID'])) {
            netsound_cart_modify($row['ting_object_id'], 'delete');
            continue;
          }

          $rows[] = elib_displaybookNEW($object, '', 'small_rm');
        }

        // Build content and cache the result.
        $content = implode($rows);
        _netsound_cart_cache_set($content, $user->uid);
      }

      if ($content == '') {
        $blocks['content'] = t('Der er ingen bøger på din huskeliste');
      }
      else {
        $blocks['content'] = $content;
      }

      break;
  }
  return $blocks;
}

/**
 * Implements hook_flush_caches().
 */
function netsound_cart_flush_caches() {
  return array('cache_netsound_cart');
}

/**
 * Helper function to store rendered "remember" lists based on user ID.
 *
 * @param type $data
 * @param type $uid
 */
function _netsound_cart_cache_set($data, $uid) {
  cache_set($uid,  serialize($data), 'cache_netsound_cart');
}

/**
 * Helper function to retrive rendered "remember" lists based on user ID.
 *
 * @param type $uid
 * @param type $reset
 * @return boolean
 */
function _netsound_cart_cache_get($uid, $reset = FALSE) {
  if (!$reset && ($cache = cache_get($uid, 'cache_netsound_cart')) && !empty($cache->data)) {
    return unserialize($cache->data);
  }
  return FALSE;
}

/**
 * Helper function to clear a single stored "remember" list for a single user.
 *
 * @param type $uid
 */
function _netsound_cart_cache_clear($uid) {
  cache_clear_all($uid, 'cache_netsound_cart');
}