<?php
/**
 * @file
 *
 */


/**
 * Implementation of hook_theme().
 */
function ebog_embed_video_theme() {
  return array(
    'ebog_embed_video' => array(
      'arguments' => array('conf' => NULL),
      'template' => 'ebog_embed_video',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function ebog_embed_video_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_block().
 */
function ebog_embed_video_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(array(
        'info' => t('Ebog Embed video'),
      ));
      break;
    case 'view':
      return array(
        'subject' => t('Ebog Embed video'),
        'content' => _ebog_embed_video_block_view(),
      );
      break;
    case 'configure':
      return _ebog_embed_video_block_configure();
    case 'save':
      _ebog_embed_video_block_save($edit);
      break;
  }
}

/**
 * Prepare and create block markup.
 *
 * @return
 *   Block HTML markup.
 */
function _ebog_embed_video_block_view() {
  $conf = array();
  $conf['embed_url'] = variable_get('ebog_embed_video_video', '');
  $conf['embed_code'] = variable_get('ebog_embed_video_embed_code', '');
  $conf['type'] = variable_get('ebog_embed_video_embed_type', '');
  $conf['title'] = variable_get('ebog_embed_video_content_title', '');
  $conf['descr'] = variable_get('ebog_embed_video_short_description', '');
  $conf['see_more_title'] = variable_get('ebog_embed_video_see_more_title', '');
  $conf['see_more_link'] = variable_get('ebog_embed_video_see_more_link', '');

  return theme('ebog_embed_video', $conf);
}

/**
 * Define some configuration fields fot the block.
 *
 * @return
 *   Form API settings form.
 */
function _ebog_embed_video_block_configure() {
  $form = array();

  $form['ebog_embed_video_video'] = array(
    '#type' => 'textfield',
    '#title' => t('URL to YouTube OR Vimeo video:'),
    '#description' => t('example: http://www.youtube.com/watch?v=XwmHoWfwHiw OR http://vimeo.com/3535418'),
    '#default_value' => variable_get('ebog_embed_video_video', ''),
  );

  $form['ebog_embed_video_short_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Short description:'),
    '#default_value' => variable_get('ebog_embed_video_short_description', ''),
  );

  $form['ebog_embed_video_content_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Content title:'),
    '#default_value' => variable_get('ebog_embed_video_content_title', ''),
  );

  $form['ebog_embed_video_see_more_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for "see more link":'),
    '#required' => TRUE,
    '#default_value' => variable_get('ebog_embed_video_see_more_title', ''),
  );

  $form['ebog_embed_video_see_more_link'] = array(
    '#type' => 'textfield',
    '#title' => t('Link for "see more link":'),
    '#maxlength' => 255,
    '#required' => TRUE,
    '#default_value' => variable_get('ebog_embed_video_see_more_link', ''),
  );

  return $form;
}

/**
 * Save block configuration.
 * @see _ebog_embed_video_block_configure().
 *
 * @param $settings
 *   Form values passes on settings form submition.
 */
function _ebog_embed_video_block_save($settings) {
  if (is_array($settings)) {
    foreach ($settings as $key => $setting) {
      variable_set($key, trim(check_plain($setting)));
    }

    $embed = ebog_embed_video_parse_url($settings['ebog_embed_video_video']);
    variable_set('ebog_embed_video_embed_code', $embed['embed_code']);
    variable_set('ebog_embed_video_embed_type', $embed['type']);
  }
}
/**
 * Parse video URL's.
 *
 * @param $url
 *   URL to parse.
 * @return
 *   Array with parsed URL and service type.
 */
function ebog_embed_video_parse_url($url) {
  $embed_url = $url;
  $embed_code = '';

  if (strpos($embed_url, 'youtube')) {
    $type = 'youtube';
    $query = parse_url($embed_url, PHP_URL_QUERY);
    $query = explode('&', $query);
    foreach ($query as $param) {
      if (strrpos($param, 'v=') == 0) {
        $embed_code = drupal_substr($param, 2);
        break;
      }
    }
  }
  elseif (strpos($embed_url, 'vimeo')) {
    $type = 'vimeo';
    $embed_code = str_replace('http://vimeo.com/', '', $embed_url);
  }
  else {
    $type = 'undefined';
  }

  return array('type' => $type, 'embed_code' => $embed_code);
}
