<?php
/**
 * @file
 * Create block with video based on video content type.
 */

/**
 * Implements hook_theme().
 */
function ebog_embed_video_theme() {
  return array(
    'ebog_embed_video' => array(
      'arguments' => array(
        'type' => NULL,
        'embed_code' => NULL,
        'description' => NULL,
        'more_link' => NULL,
      ),
      'template' => 'ebog_embed_video',
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ebog_embed_video_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_block().
 */
function ebog_embed_video_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();

  switch ($op) {
    case 'list':
      $block = array(
        array(
          'info' => t('Ebog Embed video'),
        ),
      );
      break;

    case 'view':
      $block = array(
        'subject' => t('Ebog Embed video'),
        'content' => _ebog_embed_video_block_view(),
      );
      break;
  }

  return $block;
}

/**
 * Prepare and create block markup.
 *
 * @return string
 *   Block HTML markup.
 */
function _ebog_embed_video_block_view() {
  $node = NULL;
  $content = '';

  $result = db_query('SELECT nid FROM {node} WHERE type = "video" AND status = 1 ORDER BY created DESC LIMIT 1');
  while ($row = db_fetch_array($result)) {
    $node = node_load($row['nid']);
    $embed = ebog_embed_video_parse_url($node->field_video_url[0]['value']);
    $description = check_plain($node->field_video_description[0]['value']);
    $more_link = l($node->field_more_link[0]['value'], $node->field_more_link_url[0]['value']);

    $content = theme('ebog_embed_video', $embed['type'], $embed['embed_code'], $description, $more_link);
  }

  return $content;
}

/**
 * Parse video URL's.
 *
 * @param string $url
 *   URL to parse.
 *
 * @return array
 *   Array with parsed URL and service type.
 */
function ebog_embed_video_parse_url($url) {
  $embed_url = $url;
  $embed_code = '';

  if (strpos($embed_url, 'youtube')) {
    $type = 'youtube';
    $query = parse_url($embed_url, PHP_URL_QUERY);
    $query = explode('&', $query);
    foreach ($query as $param) {
      if (strrpos($param, 'v=') == 0) {
        $embed_code = drupal_substr($param, 2);
        break;
      }
    }
  }
  elseif (strpos($embed_url, 'vimeo')) {
    $type = 'vimeo';
    $embed_code = str_replace('http://vimeo.com/', '', $embed_url);
  }
  else {
    $type = 'undefined';
  }

  return array('type' => $type, 'embed_code' => $embed_code);
}
