<?php
/**
 * NetSound/Publizon stream player integration.
 */

function netsound_stream_menu() {
  $items = array();

  $menu['publizon/%/stream'] = array(
    'title' => 'Show a popup before stream',
    'description' => 'Display some user specific text and perform some check before stream.',
    'page callback' => 'elib_popup_loan_popup',
    'page arguments' => array(1, 'stream'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $menu['publizon/%/stream/request'] = array(
    'title' => 'Download ting ebook',
    'description' => 'Checker for stream abilities regarding selected book for specific user.',
    'page callback' => 'elib_popup_download_loan_initial',
    'page arguments' => array(1, 'stream'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $menu['publizon/stream/redirect'] = array(
    'title' => 'Stream sample book',
    'description' => 'Redirect to external stream domain.',
    'page callback' => 'elib_popup_stream_redirect',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_preprocess_publizon_actions().
 *
 * Adds stream ation to all action links lists.
 */
function netsound_stream_preprocess_publizon_actions(&$vars) {
  $isbn = $vars['product']->isbn;

  // Add stream action to links.
  $vars['actions'][] = array(
    '#link' => l(t('Stream'), 'publizon/' . $isbn . '/stream', array('html' => TRUE,  'attributes' => array('class' => 'stream'))),
    '#class' => 'stream',
    '#weight' => -8,
  );

  // Sort the elements to get the stream action in between the other links.
  usort($vars['actions'], 'element_sort');
}
