<?php
/**
 * @file
 * Simple banner block module.
 */

/**
 * Implements hook_block().
 */
function ebog_banner_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        array(
          'info' => t('Ebog Banner'),
        )
      );
      break;
    case 'view':
      return array(
        'subject' => t('Ebog Banner'),
        'content' => _ebog_banner_block_view(),
      );
      break;
    case 'configure':
      return _ebog_banner_block_configure();
    case 'save':
      _ebog_banner_block_save($edit);
      break;
  }
}

/**
 * Block renderer method.
 *
 * @return string
 *   Block content markup.
 *
 * @see ebog_banner_block().
 */
function _ebog_banner_block_view() {
  drupal_add_css(drupal_get_path('module', 'ebog_banner') . '/css/ebog_banner_style.css', 'file');
  $conf = array();
  $conf['image'] = variable_get('ebog_banner_image', '');
  $conf['text'] = variable_get('ebog_banner_text', '');
  $conf['url'] = variable_get('ebog_banner_url', '');
  $conf['url_text'] = variable_get('ebog_banner_url_text', '');

  return theme('ebog_banner_block', $conf);
}

/**
 * Implements hook_form_alter().
 *
 * Alter the form, so it works okay with uploads.
 * Adding such attributes in the context of the block does not work.
 */
function ebog_banner_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'block_admin_configure' && arg(4) === 'ebog_banner') {
    $form['#attributes']['enctype'] = 'multipart/form-data';
  }
}

/**
 * Block configuration method.
 *
 * @return Array
 *   Form structure.
 *
 * @see ebog_banner_block().
 */
function _ebog_banner_block_configure() {
  $form = array();

  $default_image = variable_get('ebog_banner_image', '');
  $form['ebog_banner_image'] = array(
    '#type' => 'file',
    '#title' => t('Banner image (jpeg, png, gif), hover to see the default, if any'),
    '#description' => !empty($default_image) ? theme_image($default_image, '' , '', array('width' => 100, 'height' => 100), FALSE) : t('No image'),
  );

  $form['ebog_banner_image_remove'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remove default image'),
    '#description' => t('Check this to remove the default image, if any.'),
  );

  $form['ebog_banner_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Banner text'),
    '#default_value' => variable_get('ebog_banner_text', ''),
    '#maxlength' => 1024,
    '#required' => TRUE,
  );

  $form['ebog_banner_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Banner url'),
    '#default_value' => variable_get('ebog_banner_url', ''),
    '#required' => TRUE,
  );

  $form['ebog_banner_url_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Banner url text'),
    '#default_value' => variable_get('ebog_banner_url_text', ''),
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Block on-save method.
 *
 * Here values are handled, stored as variables, as well as image uploads.
 *
 * @param Array $values
 *   Values passed from block form.
 *
 * @see ebog_banner_block().
 */
function _ebog_banner_block_save($values) {
  $source = 'ebog_banner_image';
  $fields = array(
    'ebog_banner_text',
    'ebog_banner_url',
    'ebog_banner_url_text',
  );
  $allowed_types = array(
    'image/jpeg',
    'image/png',
    'image/gif',
  );

  // Save the text values.
  foreach ($values as $key => $value) {
    if (in_array($key, $fields)) {
      variable_set($key, trim(check_plain($value)));
    }
  }

  if ($values['ebog_banner_image_remove'] === 1) {
    variable_del('ebog_banner_image');
  }
  else {
    // Handle uploads.
    $file_type = $_FILES['files']['type'][$source];
    if (in_array($file_type, $allowed_types)) {
      $file = file_save_upload('ebog_banner_image', array(), 'sites/default/files/', FILE_EXISTS_REPLACE);
      file_set_status($file, FILE_STATUS_PERMANENT);

      if (is_object($file)) {
        variable_set('ebog_banner_image', $file->filepath);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function ebog_banner_theme() {
  return array(
    'ebog_banner_block' => array(
      'arguments' => array('conf' => NULL),
      'template' => 'templates/ebog_banner_block',
    ),
  );
}
