<?php

/**
 * @file
 * Exposes a new token user-logged-in, which can take the values "Yes" for
 * current user logged in and "No" for current user _not_ logged in.
 */

/**
 * Implements hook_token_list().
 */
function user_logged_in_token_token_list($type = 'all') {
  $tokens = array();
  $tokens['user']['user-logged-in'] = t('Is the current user logged in');
  return $tokens;
}

/**
 * Implements hook_token_list().
 */
function user_logged_in_token_token_values($type, $object = NULL, $options = array()) {
  $tokens = array('user-logged-in' => 'No');

  if (user_is_logged_in()) {
    $tokens['user-logged-in'] = 'Yes';
  }

  return $tokens;
}